/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OpenSourceRouteImport } from './routes/open-source'
import { Route as GlobeRouteImport } from './routes/globe'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as DashRouteImport } from './routes/dash'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceRoute = OpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobeRoute = GlobeRouteImport.update({
  id: '/globe',
  path: '/globe',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/dash': typeof DashRoute
  '/discord': typeof DiscordRoute
  '/download': typeof DownloadRoute
  '/globe': typeof GlobeRoute
  '/open-source': typeof OpenSourceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/dash': typeof DashRoute
  '/discord': typeof DiscordRoute
  '/download': typeof DownloadRoute
  '/globe': typeof GlobeRoute
  '/open-source': typeof OpenSourceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/dash': typeof DashRoute
  '/discord': typeof DiscordRoute
  '/download': typeof DownloadRoute
  '/globe': typeof GlobeRoute
  '/open-source': typeof OpenSourceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colors'
    | '/dash'
    | '/discord'
    | '/download'
    | '/globe'
    | '/open-source'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/colors'
    | '/dash'
    | '/discord'
    | '/download'
    | '/globe'
    | '/open-source'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/colors'
    | '/dash'
    | '/discord'
    | '/download'
    | '/globe'
    | '/open-source'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorsRoute: typeof ColorsRoute
  DashRoute: typeof DashRoute
  DiscordRoute: typeof DiscordRoute
  DownloadRoute: typeof DownloadRoute
  GlobeRoute: typeof GlobeRoute
  OpenSourceRoute: typeof OpenSourceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source': {
      id: '/open-source'
      path: '/open-source'
      fullPath: '/open-source'
      preLoaderRoute: typeof OpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globe': {
      id: '/globe'
      path: '/globe'
      fullPath: '/globe'
      preLoaderRoute: typeof GlobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorsRoute: ColorsRoute,
  DashRoute: DashRoute,
  DiscordRoute: DiscordRoute,
  DownloadRoute: DownloadRoute,
  GlobeRoute: GlobeRoute,
  OpenSourceRoute: OpenSourceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
